### ISSUE TITLE
Use NLM for dither?

### ISSUE THREAD

**Issue by zvezdochiot** [foobaz/pngloss#2]
Maybe?:
```
dc[i] = color_distance(current, current+i)
dcs = sum(dc)
if (dcs > 0) {dc[i] /= dcs} else {dc[i] = 1.0/n}
ec[i] = error * dc[i]
```

**Comment by zvezdochiot** [comment]
Cast @foobaz .

**Comment by foobaz** [comment]
I'm not familiar with NLM dithering. Are you suggesting to propagate more error to nearby pixels that have a similar color to the current pixel? Can you provide any more information about this dithering technique? I found this old paper but I'm not sure it the same algorithm you're referring to: http://yoksis.bilkent.edu.tr/pdf/files/10.1109-83.597270.pdf

**Comment by zvezdochiot** [comment]
Hi @foobaz .

On the contrary. I suggested spreading the error to colors other than the current one.

**Comment by foobaz** [comment]
I tried this dithering algorithm but the results were not great. Artifacts are more noticeable and file sizes are larger. I'm attaching the source code and the sample images if you want to see. Since this experiment didn't pan out, I won't be committing it to the repository. Thanks for the interesting idea though, it was worth a shot.

[optimize_state.c.txt](https://github.com/foobaz/pngloss/files/5106178/optimize_state.c.txt)
![lena-s40](https://user-images.githubusercontent.com/2142839/90840372-af668400-e30e-11ea-9c72-22013206253a.png)
![tenko-s40](https://user-images.githubusercontent.com/2142839/90840322-8ba33e00-e30e-11ea-869f-ef47b778ec3c.png)
