### ISSUE TITLE
options->strength?

### ISSUE THREAD

**Issue by zvezdochiot** [foobaz/pngloss#4]
Hi @foobaz .

Maybe you should use an adaptive model?:

```
quantization_strength_local = abs(current_pixel - mean(current_pixel + 3x3)) * options->strength / 10
```

**Comment by rudyrichter** [comment]
do it @foobaz do it!

**Comment by foobaz** [comment]
I tried the adaptive model but it was no better than without it. Compressed images of the same filesize look about as good either way. I tried calculating VMAF scores and those were about the same too.

I think the reason it fails to have much effect is because the compression algorithm strongly favors previously used symbols. After encoding several symbols at a given strength, reducing the strength is less effective because the previous high strength is already baked into the symbol frequency table.

In case you would be interested in looking at it yourself, I am attaching the code that implements adaptive strength.
[optimize_state.c.gz](https://github.com/foobaz/pngloss/files/5321038/optimize_state.c.gz)

**Comment by zvezdochiot** [comment]
Hi @foobaz .

The adaptive model is not needed to "improve" the result, but to optimize the choice of the compression parameter. As soon as there is an opportunity to protest, I will definitely do it.

**Comment by zvezdochiot** [comment]
Hi @foobaz .

Test image:  
![origin](https://i114.fastpic.ru/big/2020/1005/64/96c3e5246bc7dcf4484865fe5ad90d64.png)  

---

Strength build constants:
```sh
pngloss test.png
```
![const](https://i114.fastpic.ru/big/2020/1005/61/3591b0fb2463c228efeae77312603461.png)  

---

Strength build adaptive:
```sh
./pngloss test.png
```
![adapt](https://i114.fastpic.ru/big/2020/1005/01/5ae555381c20c611c3780e39bf28f501.png)  

---
